# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rovers_pb2 as rovers__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rovers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoverControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/RoverControl/GetMap',
                request_serializer=rovers__pb2.Empty.SerializeToString,
                response_deserializer=rovers__pb2.MapInfo.FromString,
                _registered_method=True)
        self.GetCommands = channel.unary_unary(
                '/RoverControl/GetCommands',
                request_serializer=rovers__pb2.RoverID.SerializeToString,
                response_deserializer=rovers__pb2.Commands.FromString,
                _registered_method=True)
        self.GetMineSerialNum = channel.unary_unary(
                '/RoverControl/GetMineSerialNum',
                request_serializer=rovers__pb2.MineLocation.SerializeToString,
                response_deserializer=rovers__pb2.SerialNum.FromString,
                _registered_method=True)
        self.NotifyServer = channel.unary_unary(
                '/RoverControl/NotifyServer',
                request_serializer=rovers__pb2.BotMessage.SerializeToString,
                response_deserializer=rovers__pb2.Empty.FromString,
                _registered_method=True)
        self.MinePin = channel.unary_unary(
                '/RoverControl/MinePin',
                request_serializer=rovers__pb2.RoverInfo.SerializeToString,
                response_deserializer=rovers__pb2.Empty.FromString,
                _registered_method=True)


class RoverControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerialNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rovers__pb2.Empty.FromString,
                    response_serializer=rovers__pb2.MapInfo.SerializeToString,
            ),
            'GetCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommands,
                    request_deserializer=rovers__pb2.RoverID.FromString,
                    response_serializer=rovers__pb2.Commands.SerializeToString,
            ),
            'GetMineSerialNum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerialNum,
                    request_deserializer=rovers__pb2.MineLocation.FromString,
                    response_serializer=rovers__pb2.SerialNum.SerializeToString,
            ),
            'NotifyServer': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyServer,
                    request_deserializer=rovers__pb2.BotMessage.FromString,
                    response_serializer=rovers__pb2.Empty.SerializeToString,
            ),
            'MinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.MinePin,
                    request_deserializer=rovers__pb2.RoverInfo.FromString,
                    response_serializer=rovers__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoverControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RoverControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoverControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverControl/GetMap',
            rovers__pb2.Empty.SerializeToString,
            rovers__pb2.MapInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverControl/GetCommands',
            rovers__pb2.RoverID.SerializeToString,
            rovers__pb2.Commands.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerialNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverControl/GetMineSerialNum',
            rovers__pb2.MineLocation.SerializeToString,
            rovers__pb2.SerialNum.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverControl/NotifyServer',
            rovers__pb2.BotMessage.SerializeToString,
            rovers__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RoverControl/MinePin',
            rovers__pb2.RoverInfo.SerializeToString,
            rovers__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
