# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rovers.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rovers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crovers.proto\"\x07\n\x05\x45mpty\"[\n\x07MapInfo\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\x12\x1d\n\x07map_row\x18\x03 \x03(\x0b\x32\x0c.MapInfo.Row\x1a\x17\n\x03Row\x12\x10\n\x08mine_val\x18\x01 \x03(\x05\"\x15\n\x07RoverID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x08\x43ommands\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"(\n\x0cMineLocation\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"\x1e\n\tSerialNum\x12\x11\n\tserialNum\x18\x01 \x01(\t\"\x1e\n\nBotMessage\x12\x10\n\x08_message\x18\x01 \x01(\t2\x83\x01\n\x0cRoverControl\x12\x1c\n\x06GetMap\x12\x06.Empty\x1a\x08.MapInfo\"\x00\x12$\n\x0bGetCommands\x12\x08.RoverID\x1a\t.Commands\"\x00\x12/\n\x10GetMineSerialNum\x12\r.MineLocation\x1a\n.SerialNum\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rovers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_MAPINFO']._serialized_start=25
  _globals['_MAPINFO']._serialized_end=116
  _globals['_MAPINFO_ROW']._serialized_start=93
  _globals['_MAPINFO_ROW']._serialized_end=116
  _globals['_ROVERID']._serialized_start=118
  _globals['_ROVERID']._serialized_end=139
  _globals['_COMMANDS']._serialized_start=141
  _globals['_COMMANDS']._serialized_end=169
  _globals['_MINELOCATION']._serialized_start=171
  _globals['_MINELOCATION']._serialized_end=211
  _globals['_SERIALNUM']._serialized_start=213
  _globals['_SERIALNUM']._serialized_end=243
  _globals['_BOTMESSAGE']._serialized_start=245
  _globals['_BOTMESSAGE']._serialized_end=275
  _globals['_ROVERCONTROL']._serialized_start=278
  _globals['_ROVERCONTROL']._serialized_end=409
# @@protoc_insertion_point(module_scope)
